import flower1 from '../assets/image/flowers/flower1.png'
import flower2 from '../assets/image/flowers/flower2.png'
import flower3 from '../assets/image/flowers/flower3.png'
import flower4 from '../assets/image/flowers/flower4.png'
import flower5 from '../assets/image/flowers/flower5.png'
import flower6 from '../assets/image/flowers/flower6.png'
import flower7 from '../assets/image/flowers/flower7.png'
import flower8 from '../assets/image/flowers/flower8.png'
import flower9 from '../assets/image/flowers/flower9.png'
import nirnroot from '../assets/image/flowers/nirnroot.png'

export const cards = [
  {
    id: 1,
    image: flower1,
    name: "Barberton Daisy",
    price: "119.00",
    currency: '$',
  },
  {
    id: 2,
    image: flower2,
    name: "Angel Wing Begonia",
    price: "169.00",
    currency: '$',
  },
  {
    id: 3,
    image: flower3,
    name: "African Violet",
    price: "199.00",
    currency: '$',
    prevPrice: '229.00',
  },
  {
    id: 4,
    image: flower4,
    name: "Beach Spider Lily",
    price: "229.00",
    currency: '$',
  },
  {
    id: 5,
    image: flower5,
    name: "Blushing Bromeliad",
    price: "129.00",
    currency: '$',
  },
  {
    id: 6,
    image: flower6,
    name: "Aluminum Plant",
    price: "139.00",
    currency: '$',
  },
  {
    id: 7,
    image: flower7,
    name: "Bird's Nest Fern",
    price: "99.00",
    currency: '$',
  },
  {
    id: 8,
    image: flower8,
    name: "Broadleaf Lady Palm",
    price: "59.00",
    prevPrice: '10.00',
    currency: '$',
  },
  {
    id: 9,
    image: flower9,
    name: "Chinese Evergreen",
    price: "39.00",
    prevPrice: '229.00',
    currency: '$',
  },
  {
    id: 10,
    image: flower4,
    name: "Snake Plant",
    price: "89.00",
    currency: '$',
  },
  {
    id: 11,
    image: flower5,
    name: "Bamboo Palm",
    price: "79.00",
    currency: '$',
  },
  {
    id: 12,
    image: flower9,
    name: "Cactus",
    price: "49.00",
    currency: '$',
  },
  {
    id: 13,
    image: flower6,
    name: "Cast Iron Plant",
    price: "169.00",
    currency: '$',
  },
  {
    id: 14,
    image: flower2,
    name: "Dumb Cane",
    price: "59.00",
    currency: '$',
  },
  {
    id: 15,
    image: flower1,
    name: "Dwarf Umbrella Tree",
    price: "89.00",
    currency: '$',
  },
  {
    id: 16,
    image: flower3,
    name: "English Ivy",
    price: "69.00",
    currency: '$',
  },
  {
    id: 17,
    image: flower7,
    name: "Flamingo Lily",
    price: "119.00",
    currency: '$',
  },
  {
    id: 18,
    image: flower4,
    name: "Fiddle-leaf Fig",
    price: "189.00",
    currency: '$',
  },
  {
    id: 19,
    image: flower5,
    name: "Gardenia",
    price: "99.00",
    currency: '$',
  },
  {
    id: 20,
    image: flower2,
    name: "Hibiscus",
    price: "79.00",
    currency: '$',
  },
  {
    id: 21,
    image: flower9,
    name: "Jade Plant",
    price: "59.00",
    currency: '$',
  },
  {
    id: 22,
    image: flower8,
    name: "Kentia Palm",
    price: "129.00",
    currency: '$',
  },
  {
    id: 23,
    image: flower7,
    name: "Lavender",
    price: "69.00",
    currency: '$',
  },
  {
    id: 24,
    image: flower5,
    name: "Lucky Bamboo",
    price: "49.00",
    currency: '$',
  },
  {
    id: 25,
    image: flower6,
    name: "Madagascar Dragon Tree",
    price: "159.00",
    currency: '$',
  },
  {
    id: 26,
    image: flower4,
    name: "Maidenhair Fern",
    price: "89.00",
    currency: '$',
  },
  {
    id: 27,
    image: flower2,
    name: "Money Tree",
    price: "149.00",
    currency: '$',
  },
  {
    id: 28,
    image: flower3,
    name: "Norfolk Island Pine",
    price: "79.00",
    currency: '$',
  },
  {
    id: 29,
    image: flower9,
    name: "Orchid",
    price: "99.00",
    currency: '$',
  },
  {
    id: 30,
    image: flower1,
    name: "Palm Lily",
    price: "109.00",
    currency: '$',
  },
  {
    id: 31,
    image: flower8,
    name: "Pansy",
    price: "39.00",
    currency: '$',
  },
  {
    id: 32,
    image: flower3,
    name: "Peace Lily",
    price: "69.00",
    currency: '$',
  },
  {
    id: 33,
    image: flower5,
    name: "Peperomia",
    price: "59.00",
    currency: '$',
  },
  {
    id: 34,
    image: flower4,
    name: "Pothos",
    price: "49.00",
    currency: '$',
  },
  {
    id: 35,
    image: flower1,
    name: "Prayer Plant",
    price: "69.00",
    currency: '$',
  },
  {
    id: 36,
    image: flower6,
    name: "Rose",
    price: "89.00",
    currency: '$',
  },
  {
    id: 37,
    image: flower4,
    name: "Spider Plant",
    price: "59.00",
    currency: '$',
  },
  {
    id: 38,
    image: flower2,
    name: "Succulent",
    price: "39.00",
    currency: '$',
  },
  {
    id: 39,
    image: flower6,
    name: "Sunflower",
    price: "49.00",
    currency: '$',
  },
  {
    id: 40,
    image: flower3,
    name: "Tulip",
    price: "39.00",
    currency: '$',
  },
  {
    id: 41,
    image: nirnroot,
    name: "Nirnroot",
    price: "5000000.00",
    currency: '$',
  },
]