import flower1 from '../../assets/image/flowers/flower1.png'
import flower2 from '../../assets/image/flowers/flower2.png'
import flower3 from '../../assets/image/flowers/flower3.png'
import flower4 from '../../assets/image/flowers/flower4.png'
import flower5 from '../../assets/image/flowers/flower5.png'
import flower6 from '../../assets/image/flowers/flower6.png'
import flower7 from '../../assets/image/flowers/flower7.png'
import flower8 from '../../assets/image/flowers/flower8.png'
import flower9 from '../../assets/image/flowers/flower9.png'
import nirnroot from '../../assets/image/flowers/nirnroot.png'

export const cards = [
  {
    id: 1,
    image: flower1,
    name: "Barberton Daisy",
    category: "House Plants",
    size: "Medium",
    price: 119,
    currency: '$',
    tags: ["daisy", "house plants"],
    rate: 4,
    countReview: 15
  },
  {
    id: 2,
    image: flower2,
    name: "Angel Wing Begonia",
    category: "House Plants",
    size: "Medium",
    price: 169,
    currency: '$',
    tags: ["begonia", "potter plants"],
    rate: 3,
    countReview: 10
  },
  {
    id: 3,
    image: flower3,
    name: "African Violet",
    category: "House Plants",
    size: "Medium",
    price: 199,
    currency: '$',
    prevPrice: 229,
    tags: ["violet", "seeds"],
    isNew: true,
    rate: 5,
    countReview: 25
  },
  {
    id: 4,
    image: flower4,
    name: "Beach Spider Lily",
    category: "Small Plants",
    size: "Medium",
    price: 229,
    currency: '$',
    tags: ["spider lily", "Small plants"],
    rate: 2,
    countReview: 8
  },
  {
    id: 5,
    image: flower5,
    name: "Blushing Bromeliad",
    category: "Big Plants",
    size: "Large",
    price: 129,
    currency: '$',
    tags: ["bromeliad", "big plants"],
    isNew: true,
    rate: 0,
    countReview: 20
  },
  {
    id: 6,
    image: flower6,
    name: "Aluminum Plant",
    category: "Succulents",
    size: "Small",
    price: 139,
    currency: '$',
    tags: ["aluminum plant", "succulents"],
    rate: 3,
    countReview: 12
  },
  {
    id: 7,
    image: flower7,
    name: "Bird's Nest Fern",
    category: "Terrariums",
    size: "Medium",
    price: 99,
    currency: '$',
    tags: ["fern", "terrariums"],
    rate: 4,
    countReview: 18
  },
  {
    id: 8,
    image: flower8,
    name: "Broadleaf Lady Palm",
    category: "Gardening",
    size: "Large",
    price: 59,
    currency: "$",
    tags: ["indoor", "palm"],
    rate: 5,
    countReview: 30
  },
  {
    id: 9,
    image: flower9,
    name: "Chinese Evergreen",
    category: "Accessories",
    size: "Small",
    price: 39,
    prevPrice: 229,
    currency: "$",
    tags: ["indoor", "foliage"],
    isNew: true,
    rate: 4,
    countReview: 28
  },
  {
    id: 10,
    image: flower4,
    name: "Snake Plant",
    category: "House Plants",
    size: "Medium",
    price: 89,
    currency: "$",
    tags: ["indoor", "air purifying"],
    rate: 3,
    countReview: 15
  },
  {
    id: 11,
    image: flower5,
    name: "Bamboo Palm",
    price: 79,
    currency: "$",
    category: "House Plants",
    size: "Small",
    tags: ["indoor", "tropical"],
    rate: 4,
    countReview: 10
  },
  {
    id: 12,
    image: flower9,
    name: "Cactus",
    price: 49,
    currency: "$",
    category: "Potter Plants",
    size: "Medium",
    tags: ["succulent", "desert"],
    rate: 5,
    countReview: 15
  },
  {
    id: 13,
    image: flower6,
    name: "Cast Iron Plant",
    price: 2069,
    currency: "$",
    category: "Seeds",
    size: "Large",
    prevPrice: 2389,
    tags: ["indoor", "low light"],
    rate: 3,
    countReview: 20
  },
  {
    id: 14,
    image: flower2,
    name: "Dumb Cane",
    price: 59,
    currency: "$",
    category: "Small Plants",
    size: "Small",
    tags: ["indoor", "toxic"],
    rate: 4,
    countReview: 12
  },
  {
    id: 15,
    image: flower1,
    name: "Dwarf Umbrella Tree",
    price: 3089,
    currency: "$",
    category: "Big Plants",
    size: "Medium",
    tags: ["indoor", "tropical"],
    rate: 5,
    countReview: 25
  },
  {
    id: 16,
    image: flower3,
    name: "English Ivy",
    price: 2069,
    currency: '$',
    category: "Succulents",
    size: "Large",
    tags: ["evergreen", "trailing"],
    rate: 4,
    countReview: 18
  },
  {
    id: 17,
    image: flower7,
    name: "Flamingo Lily",
    price: 3119,
    currency: '$',
    category: "Terrariums",
    size: "Small",
    tags: ["tropical", "indoor"],
    rate: 5,
    countReview: 30
  },
  {
    id: 18,
    image: flower4,
    name: "Fiddle-leaf Fig",
    price: 189,
    currency: '$',
    category: "Gardening",
    size: "Medium",
    tags: ["ornamental", "indoor"],
    rate: 3,
    countReview: 10
  },
  {
    id: 19,
    image: flower5,
    name: "Gardenia",
    price: 99,
    currency: '$',
    category: "Accessories",
    size: "Large",
    tags: ["fragrant", "blooming"],
    rate: 4,
    countReview: 15
  },
  {
    id: 20,
    image: flower2,
    name: "Hibiscus",
    price: 79,
    currency: '$',
    category: "House Plants",
    size: "Small",
    tags: ["colorful", "outdoor"],
    rate: 5,
    countReview: 20
  },
  {
    id: 21,
    image: flower9,
    name: "Jade Plant",
    price: 59,
    currency: '$',
    category: "Potter Plants",
    size: "Medium",
    tags: ["succulent", "indoor"],
    rate: 4,
    countReview: 12
  },
  {
    id: 22,
    image: flower8,
    name: "Kentia Palm",
    price: 129,
    currency: '$',
    category: "Seeds",
    size: "Large",
    tags: ["palm", "tropical"],
    rate: 3,
    countReview: 8
  },
  {
    id: 23,
    image: flower7,
    name: "Lavender",
    price: 69,
    currency: '$',
    category: "Small Plants",
    size: "Small",
    tags: ["fragrant", "medicinal"],
    rate: 5,
    countReview: 25
  },
  {
    id: 24,
    image: flower5,
    name: "Lucky Bamboo",
    price: 49,
    currency: '$',
    category: "Big Plants",
    size: "Medium",
    prevPrice: 69,
    tags: ["bamboo", "lucky"],
    rate: 4,
    countReview: 16
  },
  {
    id: 25,
    image: flower6,
    name: "Madagascar Dragon Tree",
    price: 159,
    currency: "$",
    category: "Succulents",
    size: "Large",
    tags: ["indoor", "easy care"],
    rate: 5,
    countReview: 28
  },
  {
    id: 26,
    image: flower4,
    name: "Maidenhair Fern",
    price: 89,
    currency: "$",
    category: "Terrariums",
    size: "Small",
    rate: 4,
    countReview: 10,
    tags: ["shade-loving", "humidity-loving"]
  },
  {
    id: 27,
    image: flower2,
    name: "Money Tree",
    price: 149,
    currency: "$",
    category: "Gardening",
    size: "Medium",
    rate: 3,
    countReview: 15,
    tags: ["indoor", "good luck"]
  },
  {
    id: 28,
    image: flower3,
    name: "Norfolk Island Pine",
    price: 79,
    currency: "$",
    category: "Accessories",
    size: "Large",
    rate: 5,
    countReview: 20,
    tags: ["evergreen", "decorative"]
  },
  {
    id: 29,
    image: flower9,
    name: "Orchid",
    price: 99,
    currency: "$",
    category: "House Plants",
    size: "Small",
    rate: 4,
    countReview: 12,
    tags: ["blooming", "fragrant"]
  },
  {
    id: 30,
    image: flower1,
    name: "Palm Lily",
    price: 109,
    currency: "$",
    category: "Potter Plants",
    size: "Medium",
    rate: 5,
    countReview: 30,
    tags: ["tropical", "bold foliage"],
    isNew: true
  },
  {
    id: 31,
    image: flower8,
    name: "Pansy",
    price: 39,
    currency: "$",
    category: "House Plants",
    size: "Small",
    rate: 4,
    countReview: 8,
    tags: ["colorful", "annual"]
  },
  {
    id: 32,
    image: flower3,
    name: "Peace Lily",
    price: 69,
    currency: "$",
    category: "Potter Plants",
    size: "Medium",
    rate: 4,
    countReview: 15,
    tags: ["air purifying", "low light"]
  },
  {
    id: 33,
    image: flower5,
    name: "Peperomia",
    price: 59,
    currency: "$",
    category: "Seeds",
    size: "Large",
    rate: 4,
    countReview: 12,
    tags: ["succulent", "easy care"]
  },
  {
    id: 34,
    image: flower4,
    name: "Pothos",
    price: 49,
    currency: '$',
    category: "Small Plants",
    size: "Small",
    rate: 5,
    countReview: 25,
    tags: ["indoor", "easy maintenance"]
  },
  {
    id: 35,
    image: flower1,
    name: "Prayer Plant",
    price: 69,
    currency: '$',
    category: "Big Plants",
    size: "Medium",
    rate: 4,
    countReview: 18,
    tags: ["pet-friendly", "bright indirect light"]
  },
  {
    id: 36,
    image: flower6,
    name: "Rose",
    price: 89,
    currency: '$',
    category: "Succulents",
    size: "Large",
    rate: 4,
    countReview: 17,
    tags: ["sun-loving", "drought-tolerant"]
  },
  {
    id: 37,
    image: flower4,
    name: "Spider Plant",
    price: 59,
    currency: '$',
    category: "Terrariums",
    size: "Small",
    rate: 3,
    countReview: 14,
    tags: ["air-purifying", "low-light tolerant"]
  },
  {
    id: 38,
    image: flower2,
    name: "Succulent",
    price: 939,
    currency: '$',
    category: "Gardening",
    size: "Medium",
    rate: 5,
    countReview: 30,
    tags: ["succulents", "low-maintenance"]
  },
  {
    id: 39,
    image: flower6,
    name: "Sunflower",
    price: 4049,
    currency: '$',
    category: "Accessories",
    size: "Large",
    tags: ["sunflowers", "decorative"],
    rate: 4,
    countReview: 10
  },
  {
    id: 40,
    image: flower3,
    name: "Tulip",
    price: 2039,
    currency: '$',
    category: "House Plants",
    size: "Small",
    tags: ["bright blooms", "spring flowers"],
    rate: 3,
    countReview: 15
  },
  {
    id: 41,
    image: nirnroot,
    name: "Nirnroot",
    price: 5000,
    currency: '$',
    category: "Big Plants",
    size: "Large",
    tags: ["rare", "magical"],
    isNew: true,
    rate: 5,
    countReview: 20
  }
]
